[package]
name         = "cw-storage-plus-derive"
authors      = ["yoisha <48324733+y-pakorn@users.noreply.github.com>"]
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
repository   = { workspace = true }
readme       = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }

[lib]
proc-macro = true

[dependencies]
syn = { workspace = true, features = ["full"] }
