[workspace]
members = ["cwd", "contracts/*", "packages/*"]

[workspace.package]
version       = "0.0.0"
authors       = ["larry <gm@larry.engineer>"]
edition       = "2021"
rust-version  = "1.65"
license       = "UNLICENSED"
homepage      = "https://larry.engineer"
repository    = "https://github.com/larry0x/cw-sdk"
documentation = "https://github.com/larry0x/cw-sdk#readme"
keywords      = ["blockchain", "cosmos", "cosmwasm"]

[workspace.dependencies]
base64               = "0.13"
bcrypt               = "0.13"
bech32               = "0.9"
bip32                = "0.4"
chrono               = "0.4"
clap                 = "4"
colored              = "2"
cosmwasm-schema      = "1.2"
cosmwasm-std         = { version = "1.2", features = ["cosmwasm_1_1"] }
cosmwasm-vm          = "1.2"
cw2                  = "1.0"
cw-address-like      = { git = "https://github.com/larry0x/cw-plus-plus", rev = "09c6024" }     # TODO: update after cw-storage-plus new release
cw-bank              = { path = "./contracts/bank" }
cw-multi-test        = "0.16"
cw-optional-indexes  = { git = "https://github.com/larry0x/cw-plus-plus", rev = "09c6024" }     # TODO: update after cw-storage-plus new release
cw-ownable           = { git = "https://github.com/larry0x/cw-plus-plus", rev = "09c6024" }     # TODO: update after cw-storage-plus new release
cw-paginate          = { git = "https://github.com/larry0x/cw-plus-plus", rev = "09c6024" }     # TODO: update after cw-storage-plus new release
cw-sdk               = { path = "./packages/sdk" }
cw-server            = { path = "./packages/server" }
cw-state-machine     = { path = "./packages/state-machine" }
cw-storage-plus      = { git = "https://github.com/CosmWasm/cw-storage-plus", rev = "a45379e" } # TODO: update after cw-storage-plus new release
cw-store             = { path = "./packages/store" }
cw-token-factory     = { path = "./contracts/token-factory" }
cw-utils             = "1.0"
dialoguer            = "0.10"
hex                  = "0.4"
home                 = "0.5"
josekit              = "0.8"
k256                 = "0.11"
merk                 = { git = "https://github.com/nomic-io/merk", rev = "8009dff" }
rand_core            = "0.6"
rocksdb              = "0.18"
schemars             = "0.8"
serde                = "1.0"
serde_json           = "1.0"
sha2                 = "0.10"
tendermint           = "0.28"
tendermint-abci      = "0.28"
tendermint-rpc       = "0.28"
tendermint-proto     = "0.28"
thiserror            = "1.0"
tokio                = "1"
toml                 = "0.5"
tracing              = "0.1"
tracing-subscriber   = "0.2"

[profile.release]
codegen-units    = 1
debug            = false
debug-assertions = false
incremental      = false
lto              = true
opt-level        = 3
overflow-checks  = true
rpath            = false
