[package]
name         = "cosmwasm-schema"
authors      = [
  "Simon Warta <webmaster128@users.noreply.github.com>",
  "Ethan Frey <ethanfrey@users.noreply.github.com>",
]
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
repository   = { workspace = true }
readme       = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }

[dependencies]
cosmwasm-schema-derive = { workspace = true }
schemars               = { workspace = true }
serde                  = { workspace = true }
serde_json             = { workspace = true }
thiserror              = { workspace = true }

[dev-dependencies]
anyhow       = { workspace = true }
cosmwasm-std = { workspace = true }
semver       = { workspace = true }
tempfile     = { workspace = true }
