[package]
name         = "cw-paginate"
authors      = ["Larry Lyu <larry@cw.software>", "ekez <ekez@withoutdoing.com>"]
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
repository   = { workspace = true }
readme       = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }

[dependencies]
cosmwasm-std    = { workspace = true }
cw-storage-plus = { workspace = true }
serde           = { workspace = true }
