[package]
name         = "cw-tree"
authors      = { workspace = true }
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
repository   = { workspace = true }
readme       = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }

[features]
default = []
# Add a few query functions for debug purpose, which are typically not needed
# for normal usage
debug   = []
# Fuzz testing
fuzzing = []

[dependencies]
blake3          = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std    = { workspace = true }
cw-item-set     = { workspace = true }
cw-storage-plus = { workspace = true }
hex             = { workspace = true }
schemars        = { workspace = true }
serde           = { workspace = true }
thiserror       = { workspace = true }

[dev-dependencies]
anyhow        = { workspace = true }
# enable the debug feature for the example
cw-tree       = { workspace = true, features = ["debug"] }
rand          = { workspace = true, features = ["std", "std_rng"] }
random-string = { workspace = true }
serde_json    = { workspace = true }
test-case     = { workspace = true }
