[package]
name         = "cw-store"
authors      = { workspace = true }
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
repository   = { workspace = true }
readme       = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }

[features]
default  = ["iterator"]
# This enables iterator functionality, as exposed in cosmwasm-std/iterator
iterator = ["cosmwasm-std/iterator"]

[dependencies]
cosmwasm-std = { workspace = true }
cw-sdk       = { workspace = true }
hex          = { workspace = true }
merk         = { workspace = true }
rocksdb      = { workspace = true }
