[package]
name         = "cw-server"
authors      = { workspace = true }
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
repository   = { workspace = true }
readme       = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }

[dependencies]
cosmwasm-std     = { workspace = true }
cw-sdk           = { workspace = true }
cw-state-machine = { workspace = true }
serde_json       = { workspace = true }
tendermint-abci  = { workspace = true }
tendermint-proto = { workspace = true }
