[package]
name         = "cw-storage-plus"
authors      = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
repository   = { workspace = true }
readme       = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }

[features]
default  = ["iterator"]
iterator = ["cosmwasm-std/iterator"]
macro    = ["cw-storage-plus-derive"]

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[dependencies]
cosmwasm-std           = { workspace = true, default-features = false }
cw-storage-plus-derive = { workspace = true, optional = true }
schemars               = { workspace = true }
serde                  = { workspace = true, features = ["derive"] }

[dev-dependencies]
criterion    = { workspace = true, features = ["html_reports"] }
rand         = { workspace = true }
rand_xoshiro = { workspace = true }

[[bench]]
name    = "main"
harness = false
