[package]
name         = "cosmwasm-crypto"
authors      = ["Mauro Lacy <maurolacy@users.noreply.github.com>"]
version      = { workspace = true }
edition      = { workspace = true }
rust-version = { workspace = true }
homepage     = { workspace = true }
repository   = { workspace = true }
readme       = { workspace = true }
license      = { workspace = true }
publish      = { workspace = true }

[lib]
# See https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
bench = false

[features]
default = []

[dependencies]
digest        = { workspace = true }
ed25519-zebra = { workspace = true }
k256          = { workspace = true, features = ["ecdsa"] }
rand_core     = { workspace = true, features = ["getrandom"] }
thiserror     = { workspace = true }

[dev-dependencies]
criterion       = { workspace = true }
english-numbers = { workspace = true }
hex             = { workspace = true }
hex-literal     = { workspace = true }
serde           = { workspace = true, features = ["derive", "alloc"] }
serde_json      = { workspace = true }
sha2            = { workspace = true }

[[bench]]
name    = "main"
harness = false
